# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 40, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 230, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 150, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(250, 150, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans")
        font.setPointSize(12)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("padding-left: 5px;")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(250, 320, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(25)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(170, 65, 67);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(170, 65, 67);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(170, 65, 67);\n"
"    background-color: white;\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.lineEdit_pass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_pass.setGeometry(QtCore.QRect(250, 230, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans")
        font.setPointSize(12)
        self.lineEdit_pass.setFont(font)
        self.lineEdit_pass.setStyleSheet("padding-left: 5px;")
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LOGIN"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.label_7.setText(_translate("MainWindow", "Username:"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "username"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.lineEdit_pass.setPlaceholderText(_translate("MainWindow", "password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
